import { z } from 'zod';

export const createMemberSchema = z.object({
  memberId: z.string().optional(),
  profilePhotoUrl: z.string().optional(),
  firstName: z.string().min(1, "First name is required"),
  secondName: z.string().optional(),
  dob: z.string().optional().nullable(),
  gender: z.string().optional(),
  email: z.string().email("Invalid email"),
  phone: z.string().optional(),
  city: z.string().optional(),
  state: z.string().optional(),
  pincode: z.string().optional(),
  businessName: z.string().optional(),
  businessEstablishedOn: z.string().optional().nullable(),
  productServiceType: z.string().optional(),
  instagramLink: z.string().optional(),
  annualTurnover: z.string().optional(),
  goalAfter90Days: z.string().optional(),
  preferredSessionMode: z.string().optional(),
  gstNumber: z.string().optional(),
  marketingChannels: z.array(z.string()).optional(),
  marketingChannelName: z.string().optional(),
  domainHostingDetails: z.string().optional(),
  businessAddress: z.string().optional(),
  challenge1: z.string().optional(),
  challenge2: z.string().optional(),
  challenge3: z.string().optional(),
  hasSocialMediaManager: z.boolean().default(false),
  socialMediaManagerNote: z.string().optional(),
  hasVideoEditing: z.boolean().default(false),
  videoEditingNote: z.string().optional(),
  notes: z.string().optional(),
  membershipPlan: z.string().optional(),
  status: z.string().optional(),
  verificationStatus: z.string().optional(),
  accountManagerId: z.string().optional(),
  assignedById: z.string().optional(),
  task: z.string().optional(),
  kycDocumentUrl: z.string().optional(),
});

export const updateMemberSchema = createMemberSchema.partial();
