import { z } from 'zod';

export const createMemberSchema = z.object({
  memberId: z.string().optional(),
  profilePhotoUrl: z.string().optional(),
  firstName: z.string().min(1, "First name is required"),
  lastName: z.string().optional(),
  dob: z.string().optional().nullable(),
  gender: z.enum(['male', 'female', 'other', 'prefer_not_to_say']).optional(),
  email: z.string().email("Invalid email"),
  phone: z.string().min(10, "Phone number is required"),
  city: z.string().optional(),
  state: z.string().optional(),
  pincode: z.string().optional(),
  businessName: z.string().optional(),
  businessEstablishedOn: z.string().optional().nullable(),
  productServiceType: z.string().optional(),
  instagramLink: z.string().optional(),
  annualTurnover: z.string().optional(),
  goalAfter90Days: z.string().optional(),
  preferredSessionMode: z.enum(['online', 'offline', 'hybrid']).optional(),
  gstNumber: z.string().optional(),
  marketingChannels: z.array(z.string()).optional(),
  marketingChannelName: z.string().optional(),
  hasMarketingTeam: z.boolean().optional(),
  marketingTeamDetails: z.string().optional(),
  hasVideoEditing: z.boolean().optional(),
  videoEditingDetails: z.string().optional(),
  domainHostingDetails: z.string().optional(),
  businessAddress: z.string().optional(),
  sector: z.string().optional(),
  industry: z.string().optional(),
  subIndustry: z.string().optional(),
  businessStage: z.enum(['idea', 'startup', 'growth', 'scaling']).optional(),
  currentChallenges: z.array(z.string()).optional(),
  notes: z.string().optional(),
  membershipPlan: z.enum(['free', 'starter', 'premium', 'vip', 'enterprise']).optional(),
  status: z.enum(['active', 'inactive', 'paused', 'suspended']).optional(),
  verificationStatus: z.enum(['awaiting_kyc', 'under_review', 'verified', 'rejected']).optional(),
  accountManagerId: z.string().optional(),
  batchId: z.string().optional(),
  createdBy: z.string().optional(),
  currentTier: z.number().int().min(1).optional(),
  password: z.string().min(8, "Password must be at least 8 characters").optional(),
});

export const updateMemberSchema = createMemberSchema.partial();
